framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system

doctrine:
  dbal:
    url: "%env(DATABASE_DSN)%"

  orm:
    auto_mapping: false
    auto_generate_proxy_classes: false
    proxy_namespace: Proxies
    proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
    default_entity_manager: default
    metadata_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
    naming_strategy: doctrine.orm.naming_strategy.default
    controller_resolver:
      auto_mapping: false
    mappings:
      App\Entity:
        type: attribute
        prefix: App\Entity\
        dir: '%kernel.project_dir%/src/Entity'